name: ERPNext Probe

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number to comment on
        required: true
        default: '3'

permissions:
  contents: read
  pull-requests: write

jobs:
  probe:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.NEXTERP_HOST }}
      API_KEY: ${{ secrets.NEXTERP_API_KEY }}
      API_SECRET: ${{ secrets.NEXTERP_API_SECRET }}
      PR_NUMBER: ${{ github.event.inputs.pr_number }}
    steps:
      - name: Check secrets
        run: |
          if [ -z "$HOST" ] || [ -z "$API_KEY" ] || [ -z "$API_SECRET" ]; then
            echo "Missing one or more secrets: NEXTERP_HOST, NEXTERP_API_KEY, NEXTERP_API_SECRET" >&2
            exit 1
          fi
      - name: Probe ERPNext resources
        id: probe
        run: |
          set -e
          mkdir -p out
          auth="Authorization: token ${API_KEY}:${API_SECRET}"
          curl -sS -H "$auth" "https://${HOST}/api/resource/Customer?limit_page_length=1" | sed -n '1,60p' > out/customers.txt || true
          curl -sS -H "$auth" "https://${HOST}/api/resource/Sales%20Order?limit_page_length=1" | sed -n '1,60p' > out/sales_orders.txt || true
          curl -sS -H "$auth" "https://${HOST}/api/resource/Purchase%20Invoice?limit_page_length=1" | sed -n '1,60p' > out/purchase_invoices.txt || true
          echo "done"
      - name: Post comment to PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          customers=$(sed -n '1,60p' out/customers.txt | sed 's/`/\`/g')
          sales=$(sed -n '1,60p' out/sales_orders.txt | sed 's/`/\`/g')
          pis=$(sed -n '1,60p' out/purchase_invoices.txt | sed 's/`/\`/g')
          body=$(cat << 'EOF'
ERPNext live probe (via GitHub Actions)

Samples (first ~60 lines each):

- Customer
```
${customers}
```

- Sales Order
```
${sales}
```

- Purchase Invoice
```
${pis}
```

Notes
- Queried ERPNext directly using token auth; secrets provided via repo secrets.
- If any are empty or show an error, verify NEXTERP_* secrets in repo settings.
EOF
          )
          jq -n --arg body "$body" '{body:$body}' > /tmp/comment.json
          curl -s -X POST -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
            -d @/tmp/comment.json >/dev/null
