name: uptime-health

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve health URL
        id: vars
        run: |
          # Prefer repo secret, else Actions variable
          if [ -n "${{ secrets.HEALTH_URL }}" ]; then
            echo "url=${{ secrets.HEALTH_URL }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ vars.HEALTH_URL }}" ]; then
            echo "url=${{ vars.HEALTH_URL }}" >> $GITHUB_OUTPUT
          else
            echo "::error::HEALTH_URL not set (use repo secret or Actions variable)" && exit 1
          fi
      - name: Curl /api/health
        env:
          URL: ${{ steps.vars.outputs.url }}
        run: |
          echo "Pinging: $URL"
          for i in 1 2 3; do
            code=$(curl -s -o /tmp/health.json -w "%{http_code}" "$URL") || true
            echo "HTTP $code"
            cat /tmp/health.json || true
            if [ "$code" = "200" ] && jq -e '.ok == true' </tmp/health.json >/dev/null 2>&1; then
              echo "Health OK"; exit 0
            fi
            sleep 5
          done
          echo "::error::Health check failed" && exit 1
