name: vercel-preview

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Build
        env:
          # Dummy envs for build-time expectation only; runtime secrets are set in Vercel
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: dev
          DATABASE_URL: postgresql://user:pass@localhost:5432/erp?schema=public
        run: npm run build
